// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnl30TZzov18-frR5nrBzhof7Y-OQ1Cn4',
    appId: '1:683877933988:web:170b47d494a30ad3f61731',
    messagingSenderId: '683877933988',
    projectId: 'boto-91f43',
    authDomain: 'boto-91f43.firebaseapp.com',
    databaseURL: 'https://boto-91f43-default-rtdb.firebaseio.com',
    storageBucket: 'boto-91f43.appspot.com',
    measurementId: 'G-HNLD7CLW2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL15WQbSXiWzb8DMmD1UN1vNt-7-cGOTQ',
    appId: '1:683877933988:android:02d759f85c26d462f61731',
    messagingSenderId: '683877933988',
    projectId: 'boto-91f43',
    databaseURL: 'https://boto-91f43-default-rtdb.firebaseio.com',
    storageBucket: 'boto-91f43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2Zra6IbU3XewSKArJRDohbXWRGAWDfo',
    appId: '1:683877933988:ios:74d4a1bbee4dc56af61731',
    messagingSenderId: '683877933988',
    projectId: 'boto-91f43',
    databaseURL: 'https://boto-91f43-default-rtdb.firebaseio.com',
    storageBucket: 'boto-91f43.appspot.com',
    iosClientId: '683877933988-dtt5r2d4rfeaues1tksjhac85m2aob5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.bustracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy2Zra6IbU3XewSKArJRDohbXWRGAWDfo',
    appId: '1:683877933988:ios:74d4a1bbee4dc56af61731',
    messagingSenderId: '683877933988',
    projectId: 'boto-91f43',
    databaseURL: 'https://boto-91f43-default-rtdb.firebaseio.com',
    storageBucket: 'boto-91f43.appspot.com',
    iosClientId: '683877933988-dtt5r2d4rfeaues1tksjhac85m2aob5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.bustracking',
  );
}
